config/routes.rb
Rails.application.routes.draw do
  
if ENV["WEBPORTAL_BASEURL"] == "false" || ENV["WEBPORTAL_BASEURL"].nil?
  baseURL = '/'
else
  baseURL = ENV["WEBPORTAL_BASEURL"]
end

scope(path: baseURL) do
  
  root 'application#root'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :text_documents

  
  
  resources :targets, :customers, :sites, :users, :provisionings, except: [:destroy, :update] do
   collection do
     delete :removeAll
   end 
  end

  resources :targets, :customers, :sites, :users , except: [:destroy, :update] do
    collection do
      patch :synchronize
    end
  end

  resources :targets, :customers, :sites, :users do
    resources :provisionings, :member => { :deliver => :post}
    collection do
      patch :synchronize
    end
    member do
     patch :synchronize
     patch :provision
     patch :deprovision
    end
  end
 
  
  resources :provisionings do
    member do
      put 'deliver'
    end
  end

  
  resources :customers do

    resources :sites, :users
  end

  resources :sites do
    resources :users
  end
  

  resources  :provisionings, except: [:destroy] do
    member do
      delete :stop
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end # scope(path: baseURL) do
end # Rails.application.routes.draw do

app/models/text_document.rb
class Validate_Hash_Uniqueness < ActiveModel::Validator
  def validate(record)
    
    @object_with_same_identifierhash = TextDocument.select { |i| i.identifierhash == record[:identifierhash]  }
    
    @object_with_same_identifierhash = @object_with_same_identifierhash.select {|i| i.id != record[:id]} unless record[:id].nil?
    
          #raise record[:id].inspect
    #.select {|i| i.id != record.id}
          #raise @object_with_same_identifierhash.inspect
    
    unless @object_with_same_identifierhash.count == 0
      record.errors[:identifierhash] << "has already been taken"     
            #raise record.errors.inspect
    end
       
  end # def
end


class TextDocument < ActiveRecord::Base
  serialize :identifierhash, Hash #,JSON #, YAML #, Hash
  
  # transient field for representing :identifierhash in YAML format:
  attr_accessor :identifieryaml
  
  def identifieryaml
    return nil if identifierhash.nil? || identifierhash == {}
    
    return YAML::dump(identifierhash).gsub('--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess','').gsub(/^\n/,'')
  end
  
  
  
  # find TextDocument with a => a and b => b in the hash:
  # e.g. try with rails console:
  # TextDocument.where("identifierhash LIKE ? AND identifierhash LIKE ?", "%\na: a\n%", "%\nb: b\n%")
  # yields:
  # => #<ActiveRecord::Relation [#<TextDocument id: 2, identifierhash: {"a"=>"a", "b"=>"b"}, content: "dhgsil", created_at: "2015-06-07 17:54:54", updated_at: "2015-06-0754:54">, #<TextDocument id: 3, identifierhash: {"b"=>"b", "a"=>"a"}, content: "", created_at: "2015-06-07 17:55:18", updated_at: "2015-06-07 17:55:18">]>
  
  # to see the exact format, how the hash is stored in the database, try on rails console sth. like:
  # irb(main):062:0> TextDocument.find(2).typecasted_attribute_value("identifierhash")
  # yields:
  # TextDocument Load (1.0ms)  SELECT  "text_documents".* FROM "text_documents"  WHERE "text_documents"."id" = ? LIMIT 1  [["id", 2]]
  # => "--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\na: a\nb: b\n"
  # for 
  # irb(main):063:0> TextDocument.find(2)
  # TextDocument Load (1.0ms)  SELECT  "text_documents".* FROM "text_documents"  WHERE "text_documents"."id" = ? LIMIT 1  [["id", 2]]
  # => #<TextDocument id: 2, identifierhash: {"a"=>"a", "b"=>"b"}, content: "dhgsil", created_at: "2015-06-07 17:54:54", updated_at: "2015-06-07 17:54:54">
  
  validates :identifierhash, presence: true #,   uniqueness: true
  # uniqueness above does now work correctly, so I have created a custom validator:
  validates_with Validate_Hash_Uniqueness

end

app/controllers/text_documents_controller.rb
class TextDocumentsController < ApplicationController
  before_action :set_text_document, only: [:show, :edit, :update, :destroy]
  #skip_before_filter :verify_authenticity_token, if: :json?
  
  #skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  # replaced by (see http://stackoverflow.com/questions/9362910/rails-warning-cant-verify-csrf-token-authenticity-for-json-devise-requests)
#  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  protect_from_forgery with: :null_session, if: :json_request?

  # GET /text_documents
  # GET /text_documents.json
  def index
    
    # filtered via best match of the identifierhash
    # try: /text_documents?identifierhash[b]=b&identifierhash[a]=a
    # will return single document, if there is an exact match (in our example, if {a: a, b: b})
    # if nothing was found, we return also documents that match all parameters but may have more parameters:
    # e.g. a document with identifierhash = {a: a, b: b, c: c} will match the filter {a: a, b: b}, 
    # if there is no 
     
    if params[:filter].nil? 
      @text_documents = TextDocument.all
    else   
      @identifierhash = params[:filter].to_hash
      @text_documents = TextDocument.select{ |i| i.identifierhash == @identifierhash}
      
      # if not found, allow for a match, if all @identifierhash is included the record's hash:
      if @text_documents.count == 0
        # allow for best match. i.e. all specified parameters match, but there is no exact match:
        @text_documents = TextDocument.select{ |i| i.identifierhash == i.identifierhash.merge(@identifierhash)}
      end
    end
    
    #if @text_documents.count == 1
      
    respond_to do |format|
      format.html { @text_documents }
      format.json { @text_documents }
      format.text { 
        if @text_documents.count == 1
          @text_documents 
        else
          render json: @text_documents, status: :unprocessable_entity
          #raise "@text_documents.count = #{@text_documents.count}" #status: :unprocessable_entity
        end
        }
    end
    

          #raise @identifierhash.inspect
          #raise params[:identifierhash].class.name.inspect
          #raise @text_documents.inspect
  end

  # GET /text_documents/1
  # GET /text_documents/1.json
  def show
  end

  # GET /text_documents/new
  def new
    @text_document = TextDocument.new
          #raise @text_document.inspect
  end

  # GET /text_documents/1/edit
  def edit
    #raise "slkgehoösdrhödl"
  end

  # POST /text_documents
  # POST /text_documents.json
  def create
          #raise request.format.inspect
          #raise Proc.new { |c| c.request.format == 'application/json'}.inspect
          #raise YAML::load(text_document_params[:identifierhash]).inspect
    # convert identifierhash text to hash:
    #new_text_document_params = {}
    new_text_document_params = text_document_params
    new_text_document_params[:identifierhash] = YAML::load(text_document_params[:identifieryaml])
    #text_document_params[:identifierhash] = YAML::load(text_document_params[:identifieryaml])
    
          #raise YAML::load(text_document_params[:identifierhash]).class.name
          #raise new_text_document_params[:identifierhash].class.name
          #raise new_text_document_params[:identifierhash].inspect
    @text_document = TextDocument.new(new_text_document_params)

    respond_to do |format|
      if @text_document.save
        format.html { redirect_to @text_document, notice: 'Text document was successfully created.' }
        format.json { render :show, status: :created, location: @text_document }
      else
        format.html { render :new, new_text_document_params
              #raise new_text_document_params.inspect
          }
        format.json { render json: @text_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_documents/1
  # PATCH/PUT /text_documents/1.json
  def update
    
    new_text_document_params = text_document_params
    new_text_document_params[:identifierhash] = YAML::load(text_document_params[:identifieryaml])

    respond_to do |format|
      if @text_document.update(new_text_document_params)
        format.html { redirect_to @text_document, notice: 'Text document was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_document }
      else
        format.html { render :edit }
        format.json { render json: @text_document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_documents/1
  # DELETE /text_documents/1.json
  def destroy
    @text_document.destroy
    respond_to do |format|
      format.html { redirect_to text_documents_url, notice: 'Text document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
protected

  def json_request?
    request.format.json?
  end


private
  # Use callbacks to share common setup or constraints between actions.
  def set_text_document
    @text_document = TextDocument.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def text_document_params
    params.require(:text_document).permit(:identifierhash, :identifieryaml, :content)
  end
end

app/helpers/text_documents_helper.rb
module TextDocumentsHelper
end

app/views/text_documents/_form.html.erb
<%= form_for(@text_document) do |f| %>
  <% if @text_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_document.errors.count, "error") %> prohibited this text_document from being saved:</h2>

      <ul>
      <% @text_document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifieryaml %><br>
    <%= f.text_area :identifieryaml %>
    <% #raise @text_document.identifierhash.inspect 
    %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_documents/_sidebar.html.erb
<% myclass = 'customers' #/customers|sites|users|provisionings|targets/.match request.original_url.to_s
   case request.original_url
       when /#{myclass}(\/?(\?.*)?)?(#)?$/
%>
                <li class="sidebar-brand">
                        Customer Functions
                </li>
                <li><%= link_to 'New Customer', new_customer_path(@params) %></li>
                <% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
                <li><%= link_to 'Synchronize Customers', synchronize_customers_path, method: :patch, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
<% if ENV["WEBPORTAL_REMOVEALL_LINK_VISIBLE"] == "true" %>
                <li><%= link_to 'Clear Customers Table', removeAll_customers_path, method: :delete, data: { confirm: 'Are you sure? This will remove all Customers from the database but it will keep the targets untouched. Data not provisioned to a target will be lost.' } %></li>
<% end %>

<% if false %>
                <li><%= link_to 'Clear Table', removeAll_customers_path, method: :delete, data: { confirm: 'This will remove recursively all entries from the database (withou de-provisioning from the target system). Are you sure?' } %></li>
<% end %>
<%     when /customers\/[1-9][0-9]*$/ %>
                <li class="sidebar-brand">
                        Create/Delete ...
                </li>
                <li><%= link_to 'New Customer', new_customer_path %></li>
                <li><%= link_to 'Add Site', new_customer_site_path(@customer) %></li>
<% @provisioningobject = @customer %>
        <li><%= render 'shared/edit_link.html.erb' %></li>
		<li><%= render 'shared/provision_link.html.erb' %></li>
                <% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
                <li><%= link_to 'Synchronize', synchronize_customer_path(@customer), method: :patch, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
		<li><%= render 'shared/destroy_link.html.erb' %></li>
                <li class="hidden"><%= link_to 'Delete Customer', @customer, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                <li class="sidebar-brand">
                        Show related ...
                </li>
<% if ENV["WEBPORTAL_SIDEBAR_RELATED_COUNT_VISIBLE"] == "true" %>
                <li><%= link_to "Sites (#{ Site.where(customer_id: @customer.id).count.to_s})", customer_sites_path(customer = @customer) %></li>
<% else %>
                <li><%= link_to "Sites", customer_sites_path(customer = @customer) %></li>
<% end %>
                <li><%= link_to "Users", customer_users_path(@customer) %></li>
                <li><%= link_to 'Provisioning Tasks', customer_provisionings_path(@customer) %></li>


<% end %>     

app/views/text_documents/edit.html.erb
<h1>Editing text_document</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_document %> |
<%= link_to 'Back', text_documents_path %>

app/views/text_documents/index.html.erb
<h1>Listing text_documents</h1>

<table>
  <thead>
    <tr>
      <th>Identifierhash</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_documents.each do |text_document| %>
      <tr>
        <td><%= text_document.identifierhash %></td>
        <td><%= text_document.content %></td>
        <td><%= link_to 'Show', text_document %></td>
        <td><%= link_to 'Edit', edit_text_document_path(text_document) %></td>
        <td><%= link_to 'Destroy', text_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text document', new_text_document_path %>

app/views/text_documents/index.text.erb
<%= @text_documents.last.content %>

app/views/text_documents/new.html.erb
<h1>New text_document</h1>

<%= render 'form' %>

<%= link_to 'Back', text_documents_path %>

app/views/text_documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifierhash:</strong>
  <%= @text_document.identifierhash %>
</p>

<p>
  <strong>Content:</strong>
  <%= @text_document.content %>
</p>

<%= link_to 'Edit', edit_text_document_path(@text_document) %> |
<%= link_to 'Back', text_documents_path %>