config/routes.rb
Rails.application.routes.draw do
  
if ENV["WEBPORTAL_BASEURL"] == "false" || ENV["WEBPORTAL_BASEURL"].nil?
  baseURL = '/'
else
  baseURL = ENV["WEBPORTAL_BASEURL"]
end

scope(path: baseURL) do
  
  root 'application#root'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :text_documents

  
  
  resources :targets, :customers, :sites, :users, :provisionings, except: [:destroy, :update] do
   collection do
     delete :removeAll
   end 
  end

  resources :targets, :customers, :sites, :users , except: [:destroy, :update] do
    collection do
      patch :synchronize
    end
  end

  resources :targets, :customers, :sites, :users do
    resources :provisionings, :member => { :deliver => :post}
    collection do
      patch :synchronize
    end
    member do
     patch :synchronize
     patch :provision
     patch :deprovision
    end
  end
 
  
  resources :provisionings do
    member do
      put 'deliver'
    end
  end

  
  resources :customers do

    resources :sites, :users
  end

  resources :sites do
    resources :users
  end
  

  resources  :provisionings, except: [:destroy] do
    member do
      delete :stop
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end # scope(path: baseURL) do
end # Rails.application.routes.draw do

app/models/target.rb
class Validate_Variable_Value_Pairs < ActiveModel::Validator
# TODO: DRYing this code: this is a duplicate from app/model/provisioning.rb
  def validate(record)


    if record.configuration.nil? || record.configuration == ""
      record.errors[:configuration] << "must be of the format \"variable1=value1,variable2=value2, ... (linebreaks instead of ',' are allowed)\""
    else

      array = record.configuration.split(/,/).map(&:strip) unless record.configuration.nil?

      #postData = {}

      while array[0]
        variableValuePairArray = array.shift.split(/=/).map(&:strip)
        if variableValuePairArray.length.to_s[/^1$|^2$/]
          #postData[variableValuePairArray[0]] = variableValuePairArray[1]
        else
          record.errors[:configuration] << "must be of the format \"variable1=value1,variable2=value2, ... (linebreaks instead of ',' are allowed)\""
          #raise 'The POST data must be of the format "variable1=value1,variable2=value2, ..."'
        end
      end # while
    end # if
  end # def
end


class Target < Provisioningobject #ActiveRecord::Base

  def target
    self
  end

  def parentClass
    nil
  end

  def self.parentClass
    nil
  end

  def parent
    nil
  end
  
  def parentSym
    nil
  end
  
  def self.parentSym
    nil
  end
  
  def self.provisioningAction(method)
    nil
  end
  
  def provisioningAction(method)

    case method
      when :create
        #"action=PrepareSystem"
     # for now, since it does not work correctly and is not fully tested:
        nil
      else
        raise "Unsupported provisioning method"
    end

  end
  
  def self.childClass
    Customer
  end
  
  def childClass
    Customer
  end

  def children
    Customer.where(target_id: id).order(:name)
  end

  def provision(method, async=true)
    super
  end
  
  def recursiveConfiguration
    configuration
  end

  #belongs_to :customer

  #has_many :customers
  # replaced by:
  # we need to destroy all customers, if a target is destroyed (otherwise we get a "target does not exist" error in the site/new and user/new view):
  has_many :customers, dependent: :destroy

  validates :name, presence: true, uniqueness: true
# TODO: does not work yet for valid target configurations. Therefore commented out.
  #validates_with Validate_Variable_Value_Pairs
end

app/controllers/targets_controller.rb
class TargetsController < ProvisioningobjectsController #ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  # GET /targets
  # GET /targets.json
  def index
    super
    #@targets = Target.all
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  # POST /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: 'Target was successfully destroyed.' }
      format.json { head :no_content }
      # needed for ajax according to http://stackoverflow.com/questions/22879329/rails-ajax-with-post-function-why-template-missing
      format.js { render nothing: true }
    end
  end

  # PATCH       /target/1/provision
  def provision
    super
  end # def provision

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_params
      params.require(:target).permit(:name, :configuration)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_for(@target) do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% @target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :size => 60%>
  </div>
  <div class="field">
    <%= f.label :configuration %><br>
    <%= f.text_area :configuration, :size => "60x20" %>
  </div>
  <div class="field">
  <%= f.submit 'Save', class: "btn btn-default" %>
  <% begin %>
     <%= link_to 'Cancel', target_path(@target), class: "btn btn-default" %>
  <% rescue %>
     <%= link_to 'Cancel', targets_path, class: "btn btn-default" %>
  <% end %>
  </div>
</div>

<% end %>

app/views/targets/_sidebar.html.erb
<% myclass = 'targets' #/customers|sites|users|provisionings|targets/.match request.original_url.to_s
   case request.original_url
       when /#{myclass}(\/?(\?.*)?)?(#)?$/
%>
                <li class="sidebar-brand">
                        Functions
                </li>
                <li><%= link_to 'New Target', new_target_path(@params) %></li>

<%     when /#{myclass}\/[1-9][0-9]*$/ %>
                <li class="sidebar-brand">
                        Create
                </li>
                <li><%= link_to 'New Target', new_target_path %></li>
                <li><%= link_to 'Add Customer', new_customer_path(target_id: @target.id) %></li>
                <li class="sidebar-brand">
                        Change/Delete
                </li>
                <li><%= link_to 'Edit Target', edit_target_path(@target) %></li>
<% if ENV["WEBPORTAL_PROVISIONINGBUTTON_TARGET_VISIBLE"] == "true" %>
                <% @provisioningobject = @target %>
		<li><%= render 'shared/provision_link.html.erb' %></li>
<% end %>
         <% if false %>
                <% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
                <li><%= link_to 'Synchronize', synchronize_target_path(@target), method: :patch, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
         <% end %>
                <li><%= link_to 'Delete Target', @target, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                <li class="sidebar-brand">
                        Show related...
                </li>
                <li><%= link_to 'Customers', "#{customers_path}?target_id=#{@target.id}" %></li>
                <li><%= link_to 'Sites', "#{sites_path}?target_id=#{@target.id}" %></li>
                <li><%= link_to 'Users', "#{users_path}?target_id=#{@target.id}" %></li>


<% end %>     

app/views/targets/edit.html.erb
	<h1>
		Edit Target	
	</h1>

<%= render 'form' %>

app/views/targets/index.html.erb
<script>
//document.getElementById('2_fullconfig').style.display='block';
//document.getElementById('2').style.display='none';
    function toggleshowhide(id) {
        if(document.getElementById(id + '_fullconfig').style.display=='none') {
            console.log('showing full config of id=' + id + '_fullconfig');
            document.getElementById(id + '_fullconfig').style.display='block';
            document.getElementById(id).style.display='none';
        } else {
            console.log('hiding full config of id=' + id + '_fullconfig');
            document.getElementById(id + '_fullconfig').style.display='none';
            document.getElementById(id).style.display='block';
        }
        return false;
    }
</script>

<h1>Targets</h1>

<div>
<%= paginate @provisioningobjects %>
</div>

<div >

<table class="refresh" id="targetIndexTable">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Configuration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
           <% showConfig = {} %>
    <% @targets.each do |target| %>
      <tr>
        <td><%= link_to target.id, target %></td>
        <td><%= link_to target.name, target %></td>
<% if false %>
        <td> <pre style="display=block;" id="<%= target.id %>" onclick="toggleshowhide(<%= target.id %>);"><%= target.configuration.to_s.gsub(/(assw[^=]*=[ ]*)([^\n\r]*).*$/, '\1*******').lines.first.to_s.gsub(/[\n\r]*/, '') + "..." %></pre>
             <pre style="display=none;" id="<%= target.id %>_fullconfig" onclick="toggleshowhide(<%= target.id %>);"><%= target.configuration.to_s.gsub(/(assw[^=]*=[ ]*)([^\r]*).*$/, '\1*******') %></pre>
        </td>
<% else %>
	<td>
        <pre><%= link_to target.configuration.to_s.gsub(/(assw[^=]*=[ ]*)([^\n\r]*).*$/, '\1*******').lines.first.to_s.gsub(/[\n\r]*/, '') + "...", target_path(target.id) %></pre>
	</td>
<% end %>
        <td><%= link_to 'Edit', edit_target_path(target), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', target, method: :delete, class: "btn btn-default", data: { confirm: 'Are you sure?' } %></td>
      </tr>
<script>
toggleshowhide("<%= target.id %>");
</script>
    <% end %>
  </tbody>

</table>
</div>

<div>
<%= paginate @provisioningobjects %>
</div>


<script>
//document.getElementById('2_fullconfig').style.display='block';
//document.getElementById('2').style.display='none';
    function toggleshowhide(id) { 
        if(document.getElementById(id + '_fullconfig').style.display=='none') { 
            console.log('showing full config of id=' + id + '_fullconfig');
            document.getElementById(id + '_fullconfig').style.display='block';
            document.getElementById(id).style.display='none';
        } else {
            console.log('hiding full config of id=' + id + '_fullconfig');
            document.getElementById(id + '_fullconfig').style.display='none';
            document.getElementById(id).style.display='block'; 
        } 
        return false;
    } 
</script>

app/views/targets/new.html.erb
<h1>New Target</h1>


<%= render 'form' %>

app/views/targets/show.html.erb
                        <h1>Target <%= @target.name %></h1>
                        <p>Manage Provisioning Targets</p>
<!-- <div class="view"> -->
<div>
  	<table>
  		<thead>
  			<th>Attribute</th>
			<th>Value	</th>
  		</thead>

  		<tbody>

			<% @target.attributes.each do |attribute| %> 
			<tr>
			    <td><%= attribute[0] %></td>
			    <td>
<% if attribute[0] == "configuration" %><pre><% end %>
<%= attribute[1].to_s.gsub(/(assw[^=]*=[ ]*)([^\r]*).*$/, '\1*******') unless attribute[1].nil? %>
<% if attribute[0] == "configuration" %></pre><% end %>
			    </td>
			</tr>
			<% end %>
			
			
		</tbody>
	</table>
</div>