config/routes.rb
Rails.application.routes.draw do
  
if ENV["WEBPORTAL_BASEURL"] == "false" || ENV["WEBPORTAL_BASEURL"].nil?
  baseURL = '/'
else
  baseURL = ENV["WEBPORTAL_BASEURL"]
end

scope(path: baseURL) do
  
  root 'application#root'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :text_documents

  
  
  resources :targets, :customers, :sites, :users, :provisionings, except: [:destroy, :update] do
   collection do
     delete :removeAll
   end 
  end

  resources :targets, :customers, :sites, :users , except: [:destroy, :update] do
    collection do
      patch :synchronize
    end
  end

  resources :targets, :customers, :sites, :users do
    resources :provisionings, :member => { :deliver => :post}
    collection do
      patch :synchronize
    end
    member do
     patch :synchronize
     patch :provision
     patch :deprovision
    end
  end
 
  
  resources :provisionings do
    member do
      put 'deliver'
    end
  end

  
  resources :customers do

    resources :sites, :users
  end

  resources :sites do
    resources :users
  end
  

  resources  :provisionings, except: [:destroy] do
    member do
      delete :stop
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end # scope(path: baseURL) do
end # Rails.application.routes.draw do

app/models/customer.rb
class ValidateTargetExists < ActiveModel::Validator
  def validate(record)
      if Customer.parentClass.exists? id: record.target_id
        return true
      else
        record.errors[:target_id] << "id=#{record.target_id} does not exist in the database!"
      end
  end
end

class ValidateLanguage < ActiveModel::Validator
  def validate(record)
    #raise record.inspect
    # returnString = @customer.provision("testMode=testMode, action=Add Customer, customerName=#{customer_params[:name]}")
  end
end

class ValidateWithProvisioningEngine < ActiveModel::Validator
  def validate(record)
    # returnString = @customer.provision("testMode=testMode, action=Add Customer, customerName=#{customer_params[:name]}")
  end
end
class ValidateWithProvisioningEngine_old < ActiveModel::Validator
  def validate(record)
    require "net/http"
    require "uri"
    
    #uri = URI.parse("http://localhost/CloudWebPortal")
    uri = URI.parse(ENV["PROVISIONINGENGINE_CAMEL_URL"])
    
    #response = Net::HTTP.post_form(uri, {"testMode" => "testMode", "offlineMode" => "offlineMode", "action" => "Add Customer", "customerName" => @customer.name})
    #OV replaced by (since I want to control the timers):
    http = Net::HTTP.new(uri.host, uri.port)
    http.open_timeout = 2
    http.read_timeout = 4
    request = Net::HTTP::Post.new(uri.request_uri)
    request.set_form_data({"testMode" => "testMode", "action" => "Add Customer", "customerName" => record.name})
    
    begin
      response = http.request(request)
      responseBody = response.body[0,200]
    rescue Exception => e
      responseBody = 'ERROR: OpenScape Voice validation timeout'
    end
   
    unless responseBody.include? 'TEST MODE'
    # i.e. no error, since, if there is an error, there will be 'ERROR:' instead
      
      begin
        errormessage =  responseBody[/ERROR.*$/]
        errormessage =  errormessage[7..-1]
      rescue
        errormessage =  responseBody
      end

      #record.errors[:name] << errormessage
      record.errors[' '] << errormessage
    end
  end
end



class Customer < Provisioningobject #< ActiveRecord::Base
  def new
  end
  
  def target
    Target.find(target_id) unless target_id.nil?
  end
  
  def children
    children = Site.where(customer: id).order(:name)
# better to return an empty relation instead of nil; therefore commented out:
#    if children.count > 0
#      children
#    else
#      nil
#    end
  end
  
  def parent
    target
  end
  
  def parentClass
    Target
  end
  
  def self.parentClass
    Target
  end
  
  def parentSym
    :target
  end
  
  def self.parentSym
    :target
  end
  
  def self.childClass
    Site
  end
  
  def childClass
    Site
  end
  
  def self.provisioningAction(method, myparent=nil)
     # note: myparent is not needed for customers, but the varible is needed for Sites, so for unification, a second argument is needed
     "action=List Customers"
  end
  
  def provisioningAction(method)
   
    case method
      when :create
        "action=Add Customer, customerName=#{name}, customerLanguage=#{language}"
      when :destroy
        if name.nil?
          raise "cannot de-provision customer without name"
        end
        "action=Delete Customer, customerName=#{name}"
      when :read
	#"action=List Customers"
        "action=List Customers, customerName=#{name}"
      else
        raise "Unsupported provisioning method"
    end
  end
  
  def self.xmlElements(xml_data)
    doc = REXML::Document.new(xml_data)
    myelements = doc.root.elements["GetBGListData"]
    
    myelements.each do |element|
      # skip special customer (BG) named BG_DC
          #raise myelements.class.inspect
      myelements.delete_element(element) if /\ABG_DC\Z/.match(element.text)
    end
    
    myelements.elements
  end
  
  def self.find_from_REXML_element(element, mytarget)
    self.where(name: element.text, target_id: mytarget.id)
  end
  
  def self.create_from_REXML_element(element, mytarget)
    self.new(name: element.text, target_id: mytarget.id)
  end

  if false
  def self.synchronizeAllOld(targets = nil, async=true, recursive=false)
    # now replaced by Provisioningobject.synchronizeAll

    targets ||= Target.all
    if async
      returnBody = delay.synchronizeAllSynchronously(targets, recursive)
    else
      returnBody = synchronizeAllSynchronously(targets, recursive)
    end
  end
  end

# TODO: remove after successful test on physical systems
if false
  def self.synchronizeAllSynchronouslyOld(targets, recursive=false)
    targets.each do |mytarget|
		#raise mytarget.inspect
      #responseBody = Customer::provision(:read, false, Customer, mytarget)
      #responseBody = Customer.read(mytarget)
      responseBody = self.read(mytarget)
		#raise responseBody
      # error handling:
      raise "synchronizeAllSynchronously(: ERROR: provisioningRequest timeout reached!" if responseBody.nil?

      # depending on the result, targetobject.provision can return a Fixnum. We need to convert this to a String
      responseBody = "synchronizeAllSynchronously: ERROR: #{self.class.name} does not exist" if responseBody.is_a?(Fixnum) && responseBody == 101

      # raise, if it is still a Fixnum:
      raise "synchronizeAllSynchronously: ERROR: wrong responseBody type (#{responseBody.class.name}) instead of String)" unless responseBody.is_a?(String)
      # business logic error:
      raise "received an ERROR response for provision(:read) in synchronizeAllSynchronously" unless responseBody[/ERROR.*$/].nil?
    
      require 'rexml/document'
      xml_data = responseBody
      doc = REXML::Document.new(xml_data)
      
            #raise doc.root.elements["GetBGListData"].elements.inspect
      doc.root.elements["GetBGListData"].elements.each do |element|
		        #raise element.text.inspect
        # skip special customer (BG) named BG_DC
        next if /\ABG_DC\Z/.match( element.text )
        # skip if the customer exists already in the database:
		        #raise xml_data.inspect
		        #raise element.text.inspect
        #next if Customer.where(name: element.text).count > 0
        #next if Customer.where(name: element.text, target_id: mytarget.id).count > 0
        next if self.where(name: element.text, target_id: mytarget.id).count > 0
		        #raise element.text
  
        # found an object that is not in the DB:
        newProvisioningobject = self.new(name: element.text, target_id: mytarget.id, status: 'provisioning successful (verified existence)')
  
        # today, it is not possible to read the language etc from Camel PE, so we cannot save with validations.
        # save it with no validations. 
        newProvisioningobject.save!(validate: false)
      
		#raise newCustomer.inspect
  
	#p 'SSSSSSSSSSSSSSSSSSSSSSSSS    Customer.synchronizeAll responseBody    SSSSSSSSSSSSSSSSSSSSSSSSS'
        #p responseBody.inspect
      end # doc.root.elements["GetBGListData"].elements.each do |element|
    end # targets.each do |target|
  end
  
end

 
    # see http://rails-bestpractices.com/posts/708-clever-enums-in-rails
    LANGUAGES = [LANGUAGE_ENGLISH_US = 'englishUS', LANGUAGE_ENGLISH_GB = 'englishGB', LANGUAGE_GERMAN = 'german'] # spanish, frensh, italian, portuguesePT, portugueseBR, dutch, russian, turkish

    belongs_to :target
    has_many :sites, dependent: :destroy
    has_many :provisionings
    
    validates :language, inclusion: {in: LANGUAGES}
    #validates :name, unique_on_target: {:case_sensitive => false, :myclass => self.inspect.gsub(/\(.*/,'')}
    validates :name, presence: true,
                     #uniqueness: true, 
                     uniqueness: {:case_sensitive => false},
                     length: { in: 3..20  }
    validates_format_of :name, :with => /\A[A-Za-z0-9_]{0,100}\Z/, message: "needs to consist of 3 to 20 characters: A-Z, a-z, 0-9 and/or _"
    validates :target_id, presence: true
    validates_with ValidateTargetExists
    
#    validates_with ValidateWithProvisioningEngine
#    validates_with ValidateLanguage
#    handle_asynchronously :create_on_OSV
end

app/controllers/customers_controller.rb
class CustomersController < ProvisioningobjectsController #ApplicationController

  # GET /customers
  # GET /customers.json
  def index
    super
  end

 # GET /customers/new
  def new
    super
    
        #raise @params.inspect
    
    @myparams = {"id"=>'ro', "name"=>rw, "language"=>'showLanguageDropDown', "created_at"=>'', "updated_at"=>'', "status"=>'', "target_id"=>'showTargetDropDown'}
    
    # for backwards compatibilit< (needed until views are DRYed):
    @customer = @provisioningobject    
    @target_id = @parent.id unless @parent.nil? #params[:target_id]

  end

  # GET /customers/1/edit
  def edit
    @myparams = {"id"=>ro, "name"=>rw, "language"=>'showLanguageDropDown', "customer_id"=>ro, "created_at"=>ro, "updated_at"=>ro, "status"=>ro, "target_id"=>ro }
  end

  # POST /customers
  # POST /customers.json
  def create
          #raise params.inspect
    # TODO: the next line is still needed. Is this the right place to control, whether a param is ro or rw?
    @myparams = {"id"=>'ro', "name"=>rw, "created_at"=>'', "language"=>'showLanguageDropDown', "updated_at"=>'', "status"=>'', "target_id"=>'showTargetDropDown'}

#raise @provisioningobject.inspect
    @provisioningobject = Customer.new(provisioningobject_params)
#raise @provisioningobject.inspect
    @customer = @provisioningobject
    @className = @provisioningobject.class.to_s
#raise @provisioningobject.provisioningtime.inspect

    super
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    #raise params.inspect
    @myparams = {"id"=>ro, "name"=>rw, "language"=>'showLanguageDropDown', "customer_id"=>ro, "created_at"=>ro, "updated_at"=>ro, "status"=>ro, "target_id"=>ro }
    #@provisioningobject = @customerS
    @customer = @provisioningobject
    
    #raise @provisioningobject.inspect

    super
  end

  # PATCH /customers/1/deprovision
  # PATCH /customers/1/deprovision.json
  def deprovision
    provisioningobject_provisionings_path = customer_provisionings_path(@provisioningobject, active: true )

    super
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy(deprovision = false)
    @provisioningobject = @customer
    @className = @provisioningobject.class.to_s
    @redirectPath = customers_url

    super
  end

  # allow for a possibility to remove all provisionins using a single button press:
  # see http://stackoverflow.com/questions/21489528/unable-to-delete-all-records-in-rails-4-through-link-to
  def removeAll
    @provisioningobjects = Customer.all
    @redirectPath = customers_url

    super
  end

  # PATCH /customers/1/synchronize
  # -> find single customer on target and synchronize the data to the local database
  # PATCH /customers/synchronize
  # -> find all customers of all known target (i.e. targets found in the local database), and synchronize them to the local database
  def synchronize
    # @partentTargets = nil means all parent targets for the synchronizeAll function
    @partentTargets = nil;
    @myClass = Customer

    @recursive_all = false
    @recursive_individual = true
    @id = params[:id]
    		#@partentTargets = Target.where(name: "CSL9DEV (OSV V8R0 Development Machine)")
    				#raise @partentTargets.inspect
        	# for testing:
        	#nonexistentcustomer = Customer.where(name: "ExampleCustomerV8") #, target_id: targets.last.id)
        	#nonexistentcustomer.last.destroy! unless nonexistentcustomer.count == 0
		#raise "dehgosdhgliodsf"
    super
  end

  # PATCH       /customers/1/provision
  def provision
    @provisioningobject = Customer.find(params[:id])
    
    super
  end # def provision


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provisioningobject
      @customer = Customer.find(params[:id])
      @provisioningobject = @customer
    end
 
    def set_provisioningobjects
      @customers = Customer.all
      @provisioningobjects = @customers
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def provisioningobject_params
      params.require(:customer).permit(:name, :target_id, :language, :provisioningtime)
    end


  
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<% @alwaysDropDown = true 
   inputFieldSize = 55
   placeholders = {};
   placeholders[:name] = "e.g. Unify"
%>
<% minWidthStyle = "min-width: #{(inputFieldSize*15.75/30 + 18.2-15.75)}em;"  %>
<% myreadonlystyle = "#{minWidthStyle} background:#eee none; color:#222;}"  %>
<style>
select {<%= minWidthStyle %>}
</style>

<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved</h2>

    </div>
  <% end %>
  
  <div>

</div>

  <div>
  	 <table> 
  		<thead>
  			<th>Attribute</th>
			<th>Value	</th>
  		</thead>

  		<tbody>
  		<% ro = 'readonly'; rw = 'readwrite' %>
		<% myparams = @myparams %>
		<% myparams['target_id']%>
		<% @customer.attributes.each do |attribute| %> 
			<tr>
			<% if myparams[attribute[0]] == rw %>
			    <td><%= f.label attribute[0] %></td>
		            <% if placeholders[attribute[0].to_sym].nil? %>
                            <td><%= f.text_field attribute[0], size: inputFieldSize, autofocus: true, placeholder: attribute[0]  %></td>
                            <% else %>
                            <td><%= f.text_field attribute[0], size: inputFieldSize, autofocus: true, placeholder: "#{placeholders[attribute[0].to_sym]}"  %></td>
                            <% end %>
	 		<% elsif myparams[attribute[0]] == ro %>
			    <td><%= f.label attribute[0] %></td>
			    <td><%= f.text_field attribute[0],:readonly => true, :style => myreadonlystyle %></td>
		 	<% elsif myparams[attribute[0]] == 'showTargetDropDown' %>
			    <td><%= f.label attribute[0] %></td>
			    <td>
			    <% selected = @parent.id unless @parent.nil? %>
			    <%= f.select(:target_id, Target.all.map {|target| 
			    	targetname_or_id = ( !target.nil? && target.name.to_s != "") ? target.name : target_id.to_s
			    	#raise targetname.inspect
			    	[targetname_or_id, target.id]}, :prompt => "Select a Target", selected: selected) %>	    			    		    
			    </td>

			<% elsif myparams[attribute[0]] == 'showLanguageDropDown' %>
			    <td><%= f.label attribute[0] %></td>
			    <td>
			    	<% selected = @provisioningobject.language %>
				<%= f.select(:language, Customer::LANGUAGES.map {|language| [language,language]}, :prompt => "Select the customer main language", selected: selected) %>
			    </td>
		 	<% end %>
<% if true %>
<% if @customer.errors[attribute[0]].any? %>
			    <td>
    <div id="error_explanation">
      <% @customer.errors[attribute[0]].each do |errormessage| %>
      <li><%= "#{attribute[0].capitalize} #{errormessage}" %></li>
      <% end %>
    </div>
                            </td>
  <% end %>
<% end %>
			</tr>
			<% end %>
			    <% if true %>
                        <tr>
			    <td><%= f.label "Provisioning Schedule#{' (ignored in synchronous mode)' unless @async}"  %></td>
			    <td>
				<%= render 'shared/form_provisioningtime.html.erb', object: @provisioningobject, f: f %>
			    </td>
                        </tr>
                <% end %>
			<tr>
				<td>
				  	<%= f.submit 'Save', type: "submit", class: "btn btn-default" %>
				</td>
				<td>
				  	<% begin %>
				  	<%= link_to 'Cancel', customer_path(@customer), class: "btn btn-default"  %>
				  	<% rescue %>
				  	<%= link_to 'Cancel', customers_path, role: "button", class: "btn btn-default" %>
				  	<% end %>
				</td>
			</tr>
		</tbody>
	</table> 
	  
  </div>
<% end %>

app/views/customers/_sidebar.html.erb
<% myclass = 'customers' #/customers|sites|users|provisionings|targets/.match request.original_url.to_s
   case request.original_url
       when /#{myclass}(\/?(\?.*)?)?(#)?$/
%>
                <li class="sidebar-brand">
                        Functions
                </li>
                <% if true %>
                <% # to be replaced by the following uncommented line, if we want to provision targets as well?: %>
                <% # if @target.nil? %>
                <li><%= link_to 'New Customer', new_customer_path(@params) %></li>
                <% else %>
                <li><%= link_to 'New Customer', new_target_customer_path(@target) %></li>
                <% end %>
                <% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" && ENV["WEBPORTAL_SYNCHRONIZEALLBUTTON_VISIBLE"] == "true" %>
                <li><%= link_to 'Synchronize Customers', synchronize_customers_path, method: :patch, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
<% if ENV["WEBPORTAL_REMOVEALL_LINK_VISIBLE"] == "true" %>
                <li><%= link_to 'Clear Customers Table', removeAll_customers_path, method: :delete, data: { confirm: 'Are you sure? This will remove all Customers from the database but it will keep the targets untouched. Data not provisioned to a target will be lost.' } %></li>
<% end %>

<% if false %>
                <li><%= link_to 'Clear Table', removeAll_customers_path, method: :delete, data: { confirm: 'This will remove recursively all entries from the database (withou de-provisioning from the target system). Are you sure?' } %></li>
<% end %>
<%     when /customers\/[1-9][0-9]*$/ %>
                <li class="sidebar-brand">
                        Create/Delete ...
                </li>
                <li><%= link_to 'New Customer', new_customer_path %></li>
                <li><%= link_to 'Add Site', new_customer_site_path(@customer) %></li>
<% @provisioningobject = @customer %>
        <li><%= render 'shared/edit_link.html.erb' %></li>
		<li><%= render 'shared/provision_link.html.erb' %></li>
                <% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
                <li><%= link_to 'Synchronize', synchronize_customer_path(@customer), method: :patch, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
		<li><%= render 'shared/destroy_link.html.erb' %></li>
                <li class="hidden"><%= link_to 'Delete Customer', @customer, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                <li class="sidebar-brand">
                        Show related ...
                </li>
<% if ENV["WEBPORTAL_SIDEBAR_RELATED_COUNT_VISIBLE"] == "true" %>
                <li><%= link_to "Sites (#{ Site.where(customer_id: @customer.id).count.to_s})", customer_sites_path(customer = @customer) %></li>
<% else %>
                <li><%= link_to "Sites", customer_sites_path(customer = @customer) %></li>
<% end %>
                <li><%= link_to "Users", customer_users_path(@customer) %></li>
                <li><%= link_to 'Provisioning Tasks', customer_provisionings_path(@customer) %></li>


<% end %>     

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<%
  @allTargets = Target.all
  @allCustomers = Customer.all
 
  def target(customer)
    #return customer.target in a SQL optimized fashion: only one SQL request needed

    targetsOfCustomer = @allTargets.select {|target| customer.target_id == target.id}
    if targetsOfCustomer.count == 1
      targetsOfCustomer[0]
    else
      raise "Did not find target of this customer=#{customer.inspect}"
    end
  end
%>
<h1>Customers</h1>

<%= render 'shared/pagination.html.erb' %>
<br />
<div>
	
<table class="refresh" id="customerIndexTable">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Target</th>
      <th>Status</th>
      <th colspan="10"></th>
    </tr>
  </thead>
  <tbody>

    <% @provisioningobjects.each do |customer| %>
      <tr>
      	<% @target = target(customer) %>
        <td><%= customer.id %></td>
        <td><%= link_to customer.name, customer %></td>
        <td>
		<% begin %>
        <%= link_to @target.name, @target %>
		<% rescue %>
      	<% end %>
        </td>
        <td class="no-refresh" id="_status<%= "#{request.path.gsub('/','_')}_#{customer.id}" %>">
          <% case customer.status
               when /success/  
                 statuscolor = "#008800"  # dark green
               when /fail/
                 statuscolor = "red"
               when /progress/
                 statuscolor = "orange"
               else
                 statuscolor = "black"
             end
          %>
   
          <%= link_to customer.status, customer_provisionings_path(customer), {:style => "color: #{statuscolor}"}%>
       </td>

        <%  @provisioningobject = customer %>
        <td><%= render 'shared/edit_button.html.erb' unless defined? edit_button_included
                edit_button %></td>
<% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
        <td><%= link_to 'Synchronize', synchronize_customer_path(customer), method: :patch, class: "btn btn-default", data: { confirm: 'Are you sure?' } %></td>
<% end %>
        <td><%= render 'shared/provision_button.html.erb' unless defined? provision_button_included
                provision_button %></td>
        <td><%= render 'shared/destroy_button.html.erb' unless defined? destroy_button_included
                destroy_button %></td>

      </tr>
    <% end %>
    <% if true %>
  </tbody>
  <% end %>
</table>
</div>

<div>
<%= paginate @provisioningobjects %>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<h1>Customer <%= @customer.name %></h1>


<div>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Customer</th>
      <th>Target/Site</th>
<% if false %>
      <th>Language</th>
<% end %>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @customer.id %></td>
        <td><%= @customer.name %></td>
        <td>
        	<% begin %>
        	<%= target = Target.find(@customer.target_id)
                    link_to target.name, target %>
        	<% rescue %>
        	[id] <%= @customer.target_id %>
        	<% end %>
        </td>
<% if false %>
        <td><%= @customer.language %></td>
<% end %>
        <td>
	   <span id="<%= "status" %>">
          <% case @customer.status
               when /success/
                 statuscolor = "#008800"  # dark green
               when /failure/
                 statuscolor = "red"
               when /progress/
                 statuscolor = "orange"
               else
                 statuscolor = "black"
             end
          %>

          <%= link_to @customer.status, customer_provisionings_path(@customer), {:style => "color: #{statuscolor}"}%>
           </span>
        </td>
<%  @provisioningobject = @customer; %>
        <td><%= render 'shared/edit_button.html.erb' 
                edit_button
            %></td>
			<% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
  <td><%= link_to 'Synchronize', synchronize_customer_path(@customer), method: :patch, class: "btn btn-default", data: { confirm: 'Are you sure?' }%></td>
			<% end %>
        <td><%= render 'shared/provision_button.html.erb' 
                provision_button
            %></td>
        <td><%= render 'shared/destroy_button.html.erb' 
                destroy_button
            %></td>

      </tr>
      <%= render @customer.sites %>
  </tbody>
</table>
</div>



<br>


<% if false %>
####### same as:
| <%= link_to "Sites of this Customer", customer_sites_path(customer_id = @customer.id) %> 
####### same as:
|
<%= link_to "Sites of this Customer", { :controller => 'sites', :action => 'index', :customer_id => customer.id } %>
<% end %>

app/views/customers/update.js.erb
  $('#<%= @customer.id %>').html("my status ajax test");
  console.log("was running update.js.erb");