config/routes.rb
Rails.application.routes.draw do
  
if ENV["WEBPORTAL_BASEURL"] == "false" || ENV["WEBPORTAL_BASEURL"].nil?
  baseURL = '/'
else
  baseURL = ENV["WEBPORTAL_BASEURL"]
end

scope(path: baseURL) do
  
  root 'application#root'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :text_documents

  
  
  resources :targets, :customers, :sites, :users, :provisionings, except: [:destroy, :update] do
   collection do
     delete :removeAll
   end 
  end

  resources :targets, :customers, :sites, :users , except: [:destroy, :update] do
    collection do
      patch :synchronize
    end
  end

  resources :targets, :customers, :sites, :users do
    resources :provisionings, :member => { :deliver => :post}
    collection do
      patch :synchronize
    end
    member do
     patch :synchronize
     patch :provision
     patch :deprovision
    end
  end
 
  
  resources :provisionings do
    member do
      put 'deliver'
    end
  end

  
  resources :customers do

    resources :sites, :users
  end

  resources :sites do
    resources :users
  end
  

  resources  :provisionings, except: [:destroy] do
    member do
      delete :stop
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end # scope(path: baseURL) do
end # Rails.application.routes.draw do

app/controllers/sites_controller.rb
class SitesController < ProvisioningobjectsController #ApplicationController

  # GET /sites
  # GET /sites.json
  def index
    super
  end
  
  def list
    if(params[:customer_id])
      #@customer = Customer.find(params[:customer_id])
      @sites = Site.find(params[:customer_id])
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new  
    super
    
    @myparams = {"id"=>'none', "name"=>rw, "customer_id"=>'showCustomerDropDown', "created_at"=>'none', "updated_at"=>'none', "status"=>'none', "sitecode"=>'none', "countrycode"=>'showDropDown', "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }

    # for backwards compatibilit< (needed until views are DRYed):
    @site = @provisioningobject
    @customer = @parent
  end

  # GET /sites/1/edit
  def edit
    # @customer is needed in the edit form (_form.html.erb)
    @customer = @site.customer
    ro = 'readonly'; rw = 'readwrite'
    #@myparams = {"id"=>ro, "name"=>rw, "customer_id"=>ro, "created_at"=>ro, "updated_at"=>ro, "status"=>ro, "sitecode"=>rw, "countrycode"=>rw, "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }
    @myparams = {"id"=>ro, "name"=>rw, "customer_id"=>ro, "created_at"=>ro, "updated_at"=>ro, "status"=>ro, "sitecode"=>rw, "countrycode"=>'showDropDown', "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }

  end

  # POST /sites
  # POST /sites.json
  def create
    #raise @parent
        # TODO: the next line is still needed. Is this the right place to control, whether a param is ro or rw?
    @myparams = {"id"=>'none', "name"=>rw, "customer_id"=>'showCustomerDropDown', "created_at"=>'none', "updated_at"=>'none', "status"=>'none', "sitecode"=>rw, "countrycode"=>'showDropDown', "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }

    @provisioningobject = Site.new(provisioningobject_params)
#raise @provisioningobject.inspect
    @site = @provisioningobject
    @className = @provisioningobject.class.to_s
#raise @provisioningobject.provisioningtime.inspect

    super
  end
  
  def createOld 
    ro = 'readonly'; rw = 'readwrite'
    #@myparams = {"id"=>'none', "name"=>rw, "customer_id"=>'showCustomerDropDown', "created_at"=>'none', "updated_at"=>'none', "status"=>'none', "sitecode"=>rw, "countrycode"=>rw, "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }
    @myparams = {"id"=>'none', "name"=>rw, "customer_id"=>'showCustomerDropDown', "created_at"=>'none', "updated_at"=>'none', "status"=>'none', "sitecode"=>rw, "countrycode"=>'showDropDown', "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }

    @object = Site.new(provisioningobject_params)
    @site = @object
    @className = @object.class.to_s
    async = true

    respond_to do |format|         
      if @object.save
        if @object.provisioningtime == Provisioningobject::PROVISIONINGTIME_IMMEDIATE && @object.provision(:create)
          @notice = "#{@className} is being created (provisioning running in the background)."
        else
          @notice = "#{@className} is created and can be provisioned ad hoc."
        end
        format.html { redirect_to @object, notice: @notice }
        format.json { render :show, status: :created, location: @object }
      else
        format.html { render :new  }                   
        format.json { render json: @object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    @myparams = {"id"=>ro, "name"=>rw, "customer_id"=>ro, "created_at"=>ro, "updated_at"=>ro, "status"=>ro, "sitecode"=>rw, "countrycode"=>'showDropDown', "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }
    @site = @provisioningobject
    super
  end
  
  def updateOld
     ro = 'readonly'; rw = 'readwrite'
    #@myparams = {"id"=>ro, "name"=>rw, "customer_id"=>ro, "created_at"=>ro, "updated_at"=>ro, "status"=>ro, "sitecode"=>rw, "countrycode"=>rw, "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }
    @myparams = {"id"=>ro, "name"=>rw, "customer_id"=>ro, "created_at"=>ro, "updated_at"=>ro, "status"=>ro, "sitecode"=>rw, "countrycode"=>'showDropDown', "areacode"=>rw, "localofficecode"=>rw, "extensionlength"=>rw, "mainextension"=>rw, "gatewayIP"=>rw }

    respond_to do |format|
      if @site.update(provisioningobject_params)
        @site.update_attributes!(:status => 'edited (provisioning status unknown)')
        format.html { redirect_to @site, notice: "Site #{@site.name} successfully updated in the database, but provisioning of target systems is not yet supported. Click \"synchronize\", for re-gaining consistency." }
        #format.html { redirect_to @site.customer, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /sites/1/synchronize
  # -> find single site on target and synchronize the data to the local database
  # PATCH /sites/synchronize
  # -> find all sites of all known customers (i.e. customers found in the local database), and synchronize them to the local database

  def synchronize
    # @partentTargets = nil means all parent targets for the synchronizeAll function
    @partentTargets = nil;
		#@partentTargets = Customer.where(name: "ExampleCustomerV8")
		#Delayed::Worker.delay_jobs = false
		#Delayed::Worker.delay_jobs = true
    @myClass = Site

    @recursive_all = false
    @recursive_individual = true
    @id = params[:id]
                #@partentTargets = Target.where(name: "CSL9DEV (OSV V8R0 Development Machine)")
                                #raise @partentTargets.inspect
                # for testing:
                #nonexistentcustomer = Customer.where(name: "ExampleCustomerV8") #, target_id: targets.last.id)
                #nonexistentcustomer.last.destroy! unless nonexistentcustomer.count == 0
                #raise "dehgosdhgliodsf"
    super
  end

  # PATCH       /sites/1/provision
  def provision    
    super
  end # def provision
  
  def provisionOld
    @site = Site.find(params[:id])
    respond_to do |format|
      if @site.provision(:create)
        #@provisionings = Provisioning.where(site: @site)
        format.html { redirect_to :back, notice: "Site #{@site.name} is being provisioned to target system(s)" }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { redirect_to :back, notice: "Site #{@site.name} could not be provisioned to target system(s)" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end # if
    end # do  
  end # def provision

  # PATCH /sites/1/deprovision
  # PATCH /sites/1/deprovision.json
  def deprovision
    provisioningobject_provisionings_path = site_provisionings_path(@provisioningobject, active: true )

    super    
  end
  
  def deprovisionOld
    @object = Site.find(params[:id])
    @className = @object.class.to_s
    @classname = @className.downcase

    if @object.activeJob?
      flash[:error] = "#{@className} #{@object.name} cannot be de-provisioned: has active jobs running: see below."
      redirectPath = customer_provisionings_path(@object, active: true )

#     not tested, therefore commented out:
#      respond_to do |format|
#        format.html { redirect_to redirectPath }
#        format.json { render json: flash[:error], status: :locked }
#      end

    elsif @object.provisioned?
      flash[:notice] = "#{@className} #{@object.name} is being de-provisioned."
      redirectPath = :back

      @object.provision(:destroy)
    else
      flash[:error] = "#{@className} #{@object.name} cannot be destroyed: is not provisioned."
      redirectPath = :back

    end

    respond_to do |format|
      format.html { redirect_to redirectPath }
      format.json { head :no_content }
    end

  end

  # DELETE /sites/1
  # DELETE /sites/1.json  
  def destroy(deprovision = false)
    @provisioningobject = @site
    @className = @provisioningobject.class.to_s

#raise request.referer.inspect
    if /sites\/[1-9][0-9]*\Z/.match(request.referer)
      @redirectPath = sites_url 
    else
      @redirectPath = :back
    end


    super
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_provisioningobject
      @site = Site.find(params[:id])
      @provisioningobject = @site
    end
    def set_provisioningobjects
      @sites = Site.all
      @provisioningobjects = @sites
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    
    def provisioningobject_params
      params.require(:site).permit(:name, :customer_id, :sitecode, :gatewayIP, :countrycode, :areacode, :localofficecode, :extensionlength, :mainextension, :provisioningtime)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/Copy of show.html.erb
<% if false %>
<% myreadonlystyle = "background:#eee none; color:#222; font-style: italic"  %>
<% else %>
<% myreadonlystyle = "background:#eee none; color:#222"  %>
<% end %>

<% ro = 'readonly'; rw = 'readwrite'; myparams = {:name => ro, :customer_id => ro,  :sitecode => ro, :gatewayIP => ro, :countrycode => ro, :areacode => ro, :localofficecode => ro, :extensionlength => ro, :mainextension => ro }%>
<%= myparams['name'] %>

<% if false %>

<h1>Site Data</h1>
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Sites', sites_path %>

<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="CSSTableGenerator">

  	<table>
  		<thead>
  			<th>Attribute</th>
			<th>Value	</th>
  		</thead>

  		<tbody>
  			<% @site.attributes.each do |attribute| %> 
			<tr>
			    <td><%= f.label attribute[0] %></td>
			    <td><%= f.label attribute[1] unless attribute[1].nil? %>
			    	
			    	
			    	<%=  attribute[0], attribute[1], myparams[attribute[0]] %>
			    </td>
			    <% if myparams[attribute[0]] == ro %>
			    <td><%= f.text_field attribute[0],:readonly => true, :style => myreadonlystyle %></td>
			    <% end %>
			</tr>
			<% end %>
			<% @site.attributes.each do |attribute| %> 
			<tr>
			    <td><%= f.label attribute[0] %></td>
			    <td><%= f.label attribute[1] unless attribute[1].nil? %></td>
			    <% if false %>
			    <td><%= f.text_field key,:readonly => true, :style => myreadonlystyle %></td>
			    <% end %>
			</tr>
			<% end %>
			
			
		</tbody>
	</table>
	  </div>
<% end %>

<% end %>

app/views/sites/___show_cakecss.html.erb
<% if false %>
<% myreadonlystyle = "background:#eee none; color:#222; font-style: italic"  %>
<% else %>
<% myreadonlystyle = "background:#eee none; color:#222"  %>
<% end %>


<h1>Site Data</h1>
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Sites', sites_path %>

<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if false %>
  <div class="CSSTableGenerator">
<% end %>
  <div class="changes view">
  
  	<dl>
			<% @site.attributes.each do |attribute| %>
			    <dt>
			    	<%= f.label attribute[0] %>
			    </dt>
			    <dd>
			    	<%= f.label attribute[1] unless attribute[1].nil? %> &nbsp; 
			    </dd>
			    <% if false %>
			    <dd>
			    	<%= f.text_field key,:readonly => true, :style => myreadonlystyle %> &nbsp; 
			    </dd>
			    <% end %>
			<% end %>
	</dl>
	  </div>
<% end %>

app/views/sites/_form.html.erb
<% @alwaysDropDown = true 
   inputFieldSize = 35
   placeholders = {};
   placeholders[:name] = "e.g. Munich" 
   placeholders[:areacode] = "e.g. 89 for Munich"
   placeholders[:localofficecode] = "e.g. 7007"
   placeholders[:extensionlength] = "e.g. 5"
   placeholders[:mainextension] = "e.g. 10000, if #{:extensionlength} = 5"
   #placeholders[:gatewayIP] = "e.g. 10.1.1.1 or gateway.domain.com (optional)"
   placeholders[:gatewayIP] = "e.g. 10.1.1.1 (optional)"
%>
<style>
select {min-width:<%= inputFieldSize*15.75/30 + 18.2 - 15.75 %>em;}
</style>


<%= form_for(@site) do |f| %>

  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  		

  <div>
  	 <table> 
  		<thead>
  			<th>Attribute</th>
			<th>Value	</th>
  		</thead>

  		<tbody>
  		<% ro = 'readonly'; rw = 'readwrite' %>
		<% myparams = @myparams %>
		<% myreadonlystyle = "background:#eee none; color:#222"  %>
		<% @site.attributes.each do |attribute| %> 				
			<% if myparams[attribute[0]] == rw %>
				<tr>
			    <td><%= f.label attribute[0] %></td>
                            <% if placeholders[attribute[0].to_sym].nil? %>
			    <td><%= f.text_field attribute[0], size: inputFieldSize, autofocus: true, placeholder: attribute[0]  %></td>
                            <% else %>
			    <td><%= f.text_field attribute[0], size: inputFieldSize, autofocus: true, placeholder: "#{placeholders[attribute[0].to_sym]}"  %></td>
                            <% end %>
			    </tr>
			<% elsif myparams[attribute[0]] == 'none' %>

			<% elsif myparams[attribute[0]] == 'showCustomerDropDown' %>
				<tr>
			    <td><%= f.label attribute[0] %></td>
			    <td>
			    <% selected = @parent.id unless @parent.nil? %>
				<%= f.select(:customer_id, Customer.where.not(target_id: nil).map {|customer| 
			    	targetname_or_id = ( !customer.nil? && !customer.target.nil? && customer.target.name.to_s != "") ? customer.target.name : customer.target_id.to_s
			    	customername_or_id = ( !customer.nil? && !customer.name.to_s != "" ) ? customer.name : customer_id.to_s
			    	#raise targetname.inspect
			    	[targetname_or_id + ":" + customername_or_id,customer.id]}, :prompt => "Select a Target:Customer", selected: selected) %>	    
<% if false %>
			        <% unless @parent.nil? %>
			        	<%= f.select(:customer_id, Customer.where.not(target_id: nil).map {|customer| [customer.target.name + ":" + customer.name,customer.id]}, :prompt => "Select a Target:Customer", :selected => @parent.id) %>
					<% else %>
						<% if true %>
			        	<%= f.select(:customer_id, Customer.where.not(target_id: nil).map {|customer| [customer.target.name + ":" + customer.name,customer.id]}, :prompt => "Select a Target:Customer") %>
			        	<% else %>
			    		<%= f.select(:customer_id, Customer.all.map {|customer| [customer.name,customer.id]}, size: inputFieldSize, :prompt => "Select a #{:customer}") %>
			    		<% end %>			    	
			    	<% end %>	
<% end %>	    
			    </td>
			    </tr>
                        <% elsif myparams[attribute[0]] == 'showDropDown' %>
                                <tr>
                            <td><%= f.label attribute[0] %></td>
			    <td><%= f.select(attribute[0], Provisioningobject::LIST[attribute[0].to_sym].map {|countrycode| [countrycode,countrycode]}, size: inputFieldSize, :prompt => "Select a #{:countrycode}") %></td>
                            </tr>
			<% else # default: show as readonly %>
				<tr>
			    <td><%= f.label attribute[0] %></td>
			    <td><%= f.text_field attribute[0], size: inputFieldSize, :readonly => true, :style => myreadonlystyle %></td>
			    </tr>
			<% end # if %>
		<% end # each %>
			    <% if true %>
                <tr>
			    <td><%= f.label "Provisioning Schedule#{' (ignored in synchronous mode)' unless @async}"  %></td>
			    <td>

				<%= render 'shared/form_provisioningtime.html.erb', object: @provisioningobject, f: f %>
			    </td>
                </tr>
                <% end %>
			<tr>
				<td>
				  	<%= f.submit 'Save', class: "btn btn-default"%>
				</td>
				<td>
				  	<% begin %>
				  	<%= link_to 'Cancel', site_path(@site), class: "btn btn-default" %>
				  	<% rescue %>
				  	<%= link_to 'Cancel', sites_path, class: "btn btn-default" %>
				  	<% end %>
				</td>
			</tr>
		</tbody>
	</table> 
	  
  </div>
<% end %>

app/views/sites/_sidebar.html.erb
<% myclass = 'sites' #/customers|sites|users|provisionings|targets/.match request.original_url.to_s
   case request.original_url
       when /#{myclass}(\/?(\?.*)?)?(#)?$/
%>
                <li class="sidebar-brand">
                        Functions
                </li>
                <% if @customer.nil? %>
                <li><%= link_to 'New Site', new_site_path(@params) %></li>
                <% else %>
                <li><%= link_to 'New Site', new_customer_site_path(@customer) %></li>
                <% end %>
                <% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" && ENV["WEBPORTAL_SYNCHRONIZEALLBUTTON_VISIBLE"] == "true" %>
                <li><%= link_to 'Synchronize Sites', synchronize_sites_path, method: :patch, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
<% if ENV["WEBPORTAL_REMOVEALL_LINK_VISIBLE"] == "true" %>
                <li><%= link_to 'Clear Sites Table', removeAll_sites_path, method: :delete, data: { confirm: 'Are you sure? This will remove all Sites from the database but it will keep the targets untouched. Data not provisioned to a target will be lost.' } %></li>
<% end %>



<%     when /#{myclass}\/[1-9][0-9]*$/ %>
                <li class="sidebar-brand">
                        Create/Delete...
                </li>
                
                <li><%= link_to 'New Site', new_site_path(@params) %></li>
                <li><%= link_to 'New User', new_site_user_path(@site) %></li>
                <% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
                <li><%= link_to 'Synchronize', synchronize_site_path(@site), method: :patch, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
<% @provisioningobject = @site %>
				<li><%= render 'shared/edit_link.html.erb' %></li>
                <li><%= render 'shared/provision_link.html.erb' %></li>
                <li><%= render 'shared/destroy_link.html.erb' %></li>
                <li class="hidden"><%= link_to 'Delete Site', @site, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                <li class="sidebar-brand">
                        Show related...
                </li>
                <% if false %>
                <li><%= link_to 'All Sites', sites_path %></li>
                <% end %>
                <li><%= link_to 'Users', site_users_path(@site) %></li>
                <li><%= link_to 'Provisioning Tasks', site_provisionings_path(@site) %></li>


<% end %>     

app/views/sites/_site.html.erb
<tr>
  <td colspan="2"></td>
  <td><%= link_to site.name, site %></td>
  <% if site.status.nil? %>
    <td></td>
  <% else %>
    <td>
      <span id="<%= "site_" + site.id.to_s %>">
          <% case site.status
               when /success/
                 statuscolor = "#008800"  # dark green
               when /failure/
                 statuscolor = "red"
               when /progress/
                 statuscolor = "orange"
               else
                 statuscolor = "black"
             end
          %>

          <%= link_to site.status, site_provisionings_path(site), {:style => "color: #{statuscolor}"}%>
        <% link_to site.status, site_provisionings_path(site) %>
      </span>
    </td>
  <% end %>
<%  @provisioningobject = site; %>
        <td><%= render 'shared/edit_button.html.erb' 
                edit_button
            %></td>
			<% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
  <td><%= link_to 'Synchronize', synchronize_site_path(site), method: :patch, class: "btn btn-default", data: { confirm: 'Are you sure?' }%></td>
			<% end %>
        <td><%= render 'shared/provision_button.html.erb' 
                provision_button
            %></td>
        <td><%= render 'shared/destroy_button.html.erb' 
                destroy_button
            %></td>
</tr>

app/views/sites/edit.html.erb
<h1>Edit Site</h1>

<%= render 'form' %>

app/views/sites/index.html.erb
<%
  @allCustomers = Customer.all
  @allTargets = Target.all

  def customer(site)
    # return site.customer in a SQL optimized fashion: only one SQL request needed

    customersOfSite = @allCustomers.select {|customer| site.customer_id == customer.id}
    if customersOfSite.count == 1
      customersOfSite[0]
    else
      nil
    end
  end

  def target(site)
    # return site.customer.target in a SQL optimized fashion: only one SQL request needed

    targetsOfSite = @allTargets.select {|target| customer(site).target_id == target.id } unless customer(site).nil?
    if targetsOfSite.nil? || targetsOfSite.count != 1
      nil
    else
      targetsOfSite[0]
    end
  end
%>

	<h1>Sites</h1>

<% if false %>
<% "this is a test of the mouse hover function. Does not work after a page-content_reload, so we need to place it somwhere, where it is not reloaded" %>
<style>
#popup {
    height: 50px;
    width: 200px;
    text-align: center;
    vertical-align:middle;
    background-color: cornflowerblue;
    color: white;
    display: none;
    padding-top: 8px;


    position: absolute;
}
</style>

<div class='user'>I am a user. Move your mouse over me</div>
<br />
<br />
<br />
<div class='user'>I am a user. Move your mouse over me</div>
<br />
<br />
<br />
<div id='popup'>Extended info about a user</div>
<div>I a piece of useless information. No use hovering over me.</div>

<script>
$('.user').hover(function() {
    $('#popup').show();
}, function() {
    $('#popup').hide();
});
</script>
<% "end of: this is a test of the mouse hover function. Does not work after a page-content_reload, so we need to place it somwhere, where it is not reloaded" %>
<% end %>
<%= render 'shared/pagination.html.erb' %>

<br />
<div>
<table class="refresh" id="siteIndexTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Target</th>
      <% if @customer.nil? %>
      <th>Customer</th>
      <% end %>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= link_to site.name, site %></td>
        <td><%= link_to target(site).name, target(site) unless target(site).nil? || target(site).name.nil? %></td>
        <% if @customer.nil? %>
        <td>
        	<% if customer(site).nil? %>
        	<%= link_to customer(site), customer(site) %>
        	<% else %>
        	<%= link_to customer(site).name, customer(site) %>
        	<% end %>       	
        </td>
        <% end %>
        <td class="no-refresh" id="_status<%= "#{request.path.gsub('/','_')}_#{site.id}" %>">
          <% case site.status
               when /success/
                 statuscolor = "#008800"  # dark green
               when /fail/
                 statuscolor = "red"
               when /progress/
                 statuscolor = "orange"
               else
                 statuscolor = "black"
             end
          %>

          <%= link_to site.status, site_provisionings_path(site), {:style => "color: #{statuscolor}"}%>
        </td>
<%  @provisioningobject = site; %>
        <td><%= render 'shared/edit_button.html.erb' unless defined? edit_button_included
                edit_button %></td>
<% if ENV["WEBPORTAL_SYNCHRONIZEBUTTON_VISIBLE"] == "true" %>
        <td><%= link_to 'Synchronize', synchronize_site_path(site), method: :patch, class: "btn btn-default", data: { confirm: 'Are you sure?' } %></td>
<% end %>
        <td><%= render 'shared/provision_button.html.erb' unless defined? provision_button_included
                provision_button %></td>
        <td><%= render 'shared/destroy_button.html.erb' unless defined? destroy_button_included
                destroy_button %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div>
<%= paginate @provisioningobjects %>
</div>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>